services:
  spark:
    image: bitnami/spark
    ports:
      - 8080:8080
      - 4040:4040
    environment:
      - SPARK_MODE=master
    networks:
      - spark-network

  python-app:
    image: ajrusso/python-app:1.0
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge